implement `wgpuComputePassEncoderSetPushConstants`
gfx-rs/wgpu-native pull request #437
Opened 2024-10-10 20:09 UTC by zackgomez

It was straightforward to implement.  I don't expect my changes to the example to be merged, I am looking for guidance on whether they should be reverted, moved to another example, or something else entirely.

Test Plan:
Modified the compute shader to use push constants.  Verified the output.

2024-10-11 07:39 UTC, rajveermalviya commented
Let's keep the `compute` example as-is, but a separate example for `push_constants` would be great to have. Also seems like `cargo fmt` CI is not happy.

2024-10-11 07:42 UTC, almarklein commented
cc @fyellin since you implemented render push constants in wgpu-py.

2024-10-11 09:48 UTC, zackgomez commented
rebased and added examples/push_constants

Also noting that I used my fork of wgpu with these PRs in a project and they all worked as expected

2024-10-11 11:53 UTC, rajveermalviya requested changes
Looks great so far! Added couple of comments.

We could also consider porting over [this wgpu test](https://github.com/gfx-rs/wgpu/blob/trunk/tests/tests/push_constants.rs) so that we have a reference to track any future wgpu-core API changes and easily update the examples if needed.

2024-10-11 11:53 UTC, rajveermalviya commented on examples/push_constants/main.c
> +#define LOG_PREFIX "[compute]"
```suggestion
#define LOG_PREFIX "[push_constants]"
```

2024-10-11 11:53 UTC, rajveermalviya commented on examples/push_constants/main.c
> +  wgpuQueueWriteBuffer(queue, storage_buffer, 0, &numbers, numbers_size);
This write is unnecessary, correct?

2024-10-11 12:02 UTC, rajveermalviya commented
Apart from the example, the API changes LGTM (and tests correctly with current example code). If you need we could merge the API changes in this PR, and do the example in a separate PR.

2024-10-12 02:13 UTC, zackgomez commented on examples/push_constants/main.c
> +#define LOG_PREFIX "[compute]"
applied

2024-10-13 00:21 UTC, fyellin commented
When will this code be available to use in wgpu-py?

2024-10-14 09:13 UTC, almarklein commented
> When will this code be available to use in wgpu-py?

@fyellin when a new version of wgpu-native is released, and wgpu-py updates to that release.

2024-10-16 19:29 UTC, zackgomez commented
pls merge

2024-10-17 05:02 UTC, rajveermalviya approved these changes
Thanks, Looks good! 

(I also added a commit to run the example in CI)

2024-10-17 07:13 UTC, merged

2024-10-17 07:13 UTC, almarklein commented
Thanks @zackgomez !